name: Test Artifact
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: requirements.txt
